Typescript and CI
Tymek/ra-language-polish pull request #4
Opened 2020-07-16 10:29 UTC by Tymek

closes #3

2020-07-20 22:07 UTC, Tymek commented
@tskorupka seems like I do have access to merge it myself, without review :confused: 

anyway, I don't think I have permission to publish it in npm. this part can be automated

2020-08-03 18:18 UTC, tskorupka requested changes
One typo fix is needed

2020-08-03 18:18 UTC, tskorupka commented on src/index.ts
> +            unsaved_changes: 'Niektóre zmiany nie zostały zapisane. Czy jesteś pewiem, że chcesz je zignorować?',
```suggestion
            unsaved_changes: 'Niektóre zmiany nie zostały zapisane. Czy jesteś pewien, że chcesz je zignorować?',
```

2020-08-03 18:34 UTC, Tymek reviewed
@tskorupka typo fixed. I also updated misleading license statement in README

2020-08-05 19:21 UTC, tskorupka approved these changes

2020-08-06 12:01 UTC, merged

2020-08-24 09:42 UTC, Tymek commented
@tskorupka I don't see new version published on npm. Could you add me as a package maintainer? [npmjs.com/~tymek](https://www.npmjs.com/~tymek)